### ISSUE TITLE
[PYTANIE] Czy biblioteka jest utrzymywana 

### ISSUE THREAD

**Issue by Immons** [przelewy24/p24-mobile-lib-xamarin#1]
Chciałbym podłączyć przelewy24 pod aplikację Xamarinową - czy jest ona utrzymywana i działa ładnie?

**Comment by przelewy24mobile** [comment]
@Immons Niestety biblioteka na platformę Xamarin nie jest już wspierana. Zachęcam do skorzystania z naszych natywnych implementacji:
https://github.com/przelewy24/p24-mobile-lib-android
https://github.com/przelewy24/p24-mobile-lib-ios

lub rozwiązania multiplatformowego opartego o framework Flutter:
https://github.com/przelewy24/p24-mobile-lib-flutter
